{% set name = "queuelib" %}
{% set version = "1.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2855162096cf0230510890b354379ea1c0ff19d105d3147d349d2433bb222b08

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8

test:
  imports:
    - queuelib
    - queuelib.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scrapy/queuelib
  summary: Collection of persistent (disk-based) queues
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
    - Gallaecio
    - kmike
    - wRAR
