schema_version: 1

context:
  version: "1.10.0"

package:
  name: queuelib
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/q/queuelib/queuelib-${{ version }}.tar.gz
  sha256: 063c821c32859ae8bdce2cc9e74156645c074218a464f8262e29a3b8de839737

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - queuelib
        - queuelib.tests
      pip_check: true
      python_version: 
        - ${{ python_min }}.*
        - "*"
  - files:
      source:
        - queuelib
    requirements:
      run:
        - python ${{ python_min }}.*
        - pytest
    script:
      - pytest queuelib

about:
  summary: Collection of persistent (disk-based) queues
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/scrapy/queuelib

extra:
  recipe-maintainers:
    - synapticarbors
    - Gallaecio
    - kmike
    - wRAR
